version: "2"
services:
  zookeeper:
    image: debezium/zookeeper:1.3
    ports:
      - 2181:2181
  kafka:
    image: debezium/kafka:1.3
    ports:
      - 9092:9092
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
  postgres:
    image: debezium/example-postgres:1.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  postgres-connector:
    image: debezium/connect:1.3
    ports:
      - 9090:8083
    links:
      - kafka
    depends_on:
      - kafka
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=pg
      - CONFIG_STORAGE_TOPIC=pg_connect_configs
      - OFFSET_STORAGE_TOPIC=pg_connect_offsets
      - STATUS_STORAGE_TOPIC=pg_connect_statuses
  cassandra-connector:
    build:
      context: ./connector
    ports:
      - 8080:8083
    links:
      - kafka
    depends_on:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=adx
      - CONFIG_STORAGE_TOPIC=cassandra_connect_configs
      - OFFSET_STORAGE_TOPIC=cassandra_connect_offsets
      - STATUS_STORAGE_TOPIC=cassandra_connect_statuses
  orders-gen:
    build:
      context: ./orders-generator
    depends_on:
      - postgres
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
